name: Auto approve
on:
  pull_request:
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  auto_approve:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: >-
      (github.event.pull_request.user.login == 'mi-wada')
      && startsWith(github.event.pull_request.title, 'Hogehoge')
      && (
        contains(github.head_ref, 'hogehoge') ||
        contains(github.head_ref, 'fugafuga')
      )
    steps:
      - env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr review --approve $PR_URL
          gh pr merge --auto --squash $PR_URL
