name: reject-not-english-PR
on:
  pull_request:
    branches: [ master ]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: detect-string
        id: detect-string
        run: |
          result=`git branch`
          echo "::set-output name=result::$result"
      - name: comment-on-PR
        env:
          RESULT: ${{steps.detext-string.outputs.result}}
        uses: actions/github-script@v4
        with:
          script: console.log(RESULT)
