name: say_hello
on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      name:
        description:  'Person to greet'
        required: true
        default: 'Mitsuaki Wada'
      home:
        description: 'location'
        required: false
        default: ${GITHUB_WORKSPACE}
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - id: say_hello
        name: "$(pwd)hoge"
        run: |
          echo "HOME: ${HOME}"
          echo ~/
          echo $(pwd)
          echo "${GITHUB_WORKSPACE} "
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"

          output="
            hello!!
            EOF






            my name is mitsuaki!
            ok!
          "
          echo $output
          echo 'name<<EOF' >> $GITHUB_OUTPUT
          echo $output >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - id: hoge
        run: |
          echo ${{ steps.say_hello.outputs.name }}
      - uses: actions/github-script@v4
        with:
          script: |
            console.log(context.repo.owner)
