name: say_hello
on:
  workflow_dispatch:
    inputs:
      name:
        description:  'Person to greet'
        required: true
        default: 'Mitsuaki Wada'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - id: say_hello
        run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
      - run: echo "say_hello output is ${{ steps.say_hello.outputs }}"
