name: say_hello
on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      name:
        description:  'Person to greet'
        required: true
        default: 'Mitsuaki Wada'
      home:
        description: 'location'
        required: false
        default: ${GITHUB_WORKSPACE}
jobs:
  say_hello:
    runs-on: ubuntu-latest
    env:
      KUSTOMIZE_VERSION: 4.2.0
    strategy:
      fail-fast: false
      matrix:
        service: ['hoge']
        environment: ['prod', 'stg', 'dev']
    steps:
      - id: dump
        run: |
          echo "${{ matrix.environment }}"
          echo "HOME: ${HOME}"
          echo ~/
          echo $(pwd)
          echo "${GITHUB_WORKSPACE} "
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
          echo "${{ github.workspace }}"

          output="
            hello!!
            EOF






            my name is mitsuaki!
            ok!
          "
          echo $output
          echo 'name<<EOF' >> $GITHUB_OUTPUT
          echo $output >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - id: cache-kustomize
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/kustomize
          key: kustomize-v2-${{ env.KUSTOMIZE_VERSION }}
      - name: install kustomize
        if: steps.cache-kustomize.outputs.cache-hit != 'true'
        run:
          echo 'hoge' >> kustomize
      - uses: actions/github-script@v4
        with:
          script: |
            console.log(context.repo.owner)
