name: .github/workflows/test_pull_request_issue_if.yml
on:
  pull_request:
    types: [closed]
  issues:
    types: [closed]
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo github.event.number = ${{ github.event.number }}
          echo github.event.issues.number = ${{ github.event.issues.number }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
